<?php
# This file was automatically generated by the MediaWiki 1.41.0-alpha
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/MainConfigSchema.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}


## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "星际公民中文百科";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "https://citizen-wiki-production.up.railway.app";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [
	'1x' => "$wgResourceBasePath/resources/assets/sitelogo.svg",
	'icon' => "$wgResourceBasePath/resources/assets/sitelogo.svg",
];

## UPO means: this is also a user preference option

$wgEnableEmail = false;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "";
$wgPasswordSender = "";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "postgres";
$wgDBserver = "containers-us-west-2.railway.app";
$wgDBname = "railway";
$wgDBuser = "postgres";
$wgDBpassword = "MHF4wzLkH2T5n64yRrI6";

# Postgres specific settings
$wgDBport = "7119";
$wgDBmwschema = "mediawiki";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = false;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

# Site language code, should be one of the list in ./includes/languages/data/Names.php
$wgLanguageCode = "zh-cn";

# Time zone
$wgLocaltimezone = "PRC";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

$wgSecretKey = "2238bfe1b497e7be3594098bb75108da21c4c66919edd2a940805dd2ac621d78";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "a3d1bb760517e203";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "https://creativecommons.org/licenses/by-nc-sa/4.0/";
$wgRightsText = "知识共享署名-非商业性使用-相同方式共享";
$wgRightsIcon = "$wgResourceBasePath/resources/assets/licenses/cc-by-nc-sa.png";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

# The following permissions were set based on your choice in the installer
$wgGroupPermissions['*']['createaccount'] = false;
$wgGroupPermissions['*']['edit'] = false;

## Default skin: you can change the default skin. Use the internal symbolic
## names, e.g. 'vector' or 'monobook':
$wgDefaultSkin = "Citizen";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'Citizen' );

# Enabled extensions. Most of the extensions are enabled by adding
# wfLoadExtension( 'ExtensionName' );
# to LocalSettings.php. Check specific extension documentation for more details.
# The following extensions were automatically enabled:
wfLoadExtension( 'AbuseFilter' );
# wfLoadExtension( 'AWS' );
wfLoadExtension( 'CategoryTree' );
wfLoadExtension( 'Cite' );
wfLoadExtension( 'CiteThisPage' );
wfLoadExtension( 'CodeEditor' );
wfLoadExtension( 'CodeMirror' );
wfLoadExtension( 'ConfirmEdit' );
wfLoadExtension( 'DynamicPageList3' );
wfLoadExtension( 'Gadgets' );
wfLoadExtension( 'ImageMap' );
wfLoadExtension( 'InputBox' );
wfLoadExtension( 'intersection' );
wfLoadExtension( 'Interwiki' );
wfLoadExtension( 'Loops' );
wfLoadExtension( 'Math' );
wfLoadExtension( 'MultimediaViewer' );
wfLoadExtension( 'Nuke' );
wfLoadExtension( 'OATHAuth' );
wfLoadExtension( 'PageImages' );
wfLoadExtension( 'ParserFunctions' );
wfLoadExtension( 'PdfHandler' );
wfLoadExtension( 'Poem' );
wfLoadExtension( 'Renameuser' );
wfLoadExtension( 'ReplaceText' );
wfLoadExtension( 'SandboxLink' );
wfLoadExtension( 'Scribunto' );
wfLoadExtension( 'SecureLinkFixer' );
wfLoadExtension( 'ShortDescription' );
wfLoadExtension( 'SpamBlacklist' );
wfLoadExtension( 'SyntaxHighlight_GeSHi' );
wfLoadExtension( 'TemplateData' );
wfLoadExtension( 'TemplateSandbox' );
wfLoadExtension( 'TemplateStyles' );
wfLoadExtension( 'TemplateStylesExtender' );
wfLoadExtension( 'TextExtracts' );
wfLoadExtension( 'TitleBlacklist' );
wfLoadExtension( 'UserGroups' );
wfLoadExtension( 'VisualEditor' );
wfLoadExtension( 'WikiEditor' );
wfLoadExtension( 'WikiSeo' );
wfLoadExtension( 'Elastica' );
wfLoadExtension( 'CirrusSearch' );

$wgDefaultUserOptions['usebetatoolbar'] = 1; // user option provided by WikiEditor extension
$wgGroupPermissions['*']['edit'] = false;
unset( $wgGroupPermissions['user'] );
# End of automatically generated settings.
# Add more configuration options below.
$wgGroupPermissions['确认用户']['browsearchive'] = true;
$wgGroupPermissions['确认用户']['createpage'] = true;
$wgGroupPermissions['确认用户']['createtalk'] = true;
$wgGroupPermissions['确认用户']['delete'] = true;
$wgGroupPermissions['确认用户']['deletedhistory'] = true;
$wgGroupPermissions['确认用户']['deletedtext'] = true;
$wgGroupPermissions['确认用户']['deleterevision'] = true;
$wgGroupPermissions['确认用户']['import'] = true;
$wgGroupPermissions['确认用户']['importupload'] = true;
$wgGroupPermissions['确认用户']['managechangetags'] = true;
$wgGroupPermissions['确认用户']['mergehistory'] = true;
$wgGroupPermissions['确认用户']['minoredit'] = true;
$wgGroupPermissions['确认用户']['move'] = true;
$wgGroupPermissions['确认用户']['move-categorypages'] = true;
$wgGroupPermissions['确认用户']['move-subpages'] = true;
$wgGroupPermissions['确认用户']['movefile'] = true;
$wgGroupPermissions['确认用户']['noratelimit'] = true;
$wgGroupPermissions['确认用户']['read'] = true;
$wgGroupPermissions['确认用户']['reupload'] = true;
$wgGroupPermissions['确认用户']['rollback'] = true;
$wgGroupPermissions['确认用户']['writeapi'] = true;
$wgGroupPermissions['确认用户']['edit'] = true;
$wgGroupPermissions['确认用户']['editinterface'] = true;
$wgGroupPermissions['确认用户']['editmyoptions'] = true;
$wgGroupPermissions['确认用户']['editmyprivateinfo'] = true;
$wgGroupPermissions['确认用户']['editmywatchlist'] = true;
# 启用VisualEditor的Wikitext
$wgVisualEditorEnableWikitext = true;
# 启用编辑模式选择列表
$wgVisualEditorUseSingleEditTab = true;
# 关闭默认编辑完毕监视页面
$wgDefaultUserOptions['watchdefault'] = 0;

# End of automatically generated settings.
# Add more configuration options below.

