name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: "PHPUnit: MW ${{ matrix.mw }}, PHP ${{ matrix.php }}"

    strategy:
      matrix:
        include:
          - mw: 'REL1_35'
            php: '8.0'
          - mw: 'REL1_38'
            php: '8.1'
          - mw: 'REL1_39'
            php: '8.1'

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mediawiki

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl
          tools: composer

      - name: Cache MediaWiki
        id: cache-mediawiki
        uses: actions/cache@v3
        with:
          path: |
            mediawiki
            !mediawiki/extensions/
            !mediawiki/vendor/
          key: mw_${{ matrix.mw }}-php${{ matrix.php }}_v3

      - name: Cache Composer cache
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: composer-php${{ matrix.php }}

      - uses: actions/checkout@v3
        with:
            path: EarlyCopy

      - name: Install MediaWiki
        if: steps.cache-mediawiki.outputs.cache-hit != 'true'
        working-directory: ~
        run: bash EarlyCopy/.github/workflows/installMediaWiki.sh ${{ matrix.mw }} SimpleBatchUpload

      - uses: actions/checkout@v3
        with:
          path: mediawiki/extensions/SimpleBatchUpload

      - run: composer update

      - name: Run update.php
        run: php maintenance/update.php --quick

      - name: Run PHPUnit
        run: php tests/phpunit/phpunit.php -c extensions/SimpleBatchUpload/

      - name: Run PHPUnit with code coverage
        run: php tests/phpunit/phpunit.php -c extensions/SimpleBatchUpload/ --coverage-clover coverage.xml

      - name: Upload code coverage
        run: bash <(curl -s https://codecov.io/bash)
        if: github.ref == 'refs/heads/master'
